version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: my_app
    environment:
      DB_URI: mongodb+srv://rr200024:OQ0PKjxnEiTRKc3s@nutriguidecluster.d3gmf.mongodb.net/
      JWT_SECRET: f5ef07ced83d13947ed88174da9004f4f0e1235a894bdbecc6a7ab8e6ddd5ea2fa929bcca5cf004714cdb284553804c6ef2591e428797d3b3adb95033bde1e6d
      FDC_API_KEY: hd7gpVnbSsuqTsfsEkqmNsgkHboftBAn0qOREL5w
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
      
  seed:
    build: .
    command: node config/seedDatabase.js
    depends_on:
      - mongo_db
    entrypoint: ["/bin/sh", "-c", "sleep 10 && node config/seedDatabase.js"]

volumes:
  mongo_data:
